### ISSUE TITLE
[Icon Request] Veracrypt, Syncthing, Asymptote

### ISSUE THREAD

**Issue by etrmrh** [vinceliuice/WhiteSur-icon-theme#11]
Hello! I love your great work so far. I want to request custom icons for [Veracrypt](https://www.veracrypt.fr/code/VeraCrypt/), [Syncthing](https://syncthing.net/), and [Asymptote](https://asymptote.sourceforge.io/) for this WhiteSur icon pack. Thank you!

**Comment by vinceliuice** [comment]
No problem!
