### ISSUE TITLE
[Quick Question] What are the Guidelines to reproduce same Icon style ?

### ISSUE THREAD

**Issue by Wilfried-1** [vinceliuice/WhiteSur-icon-theme#116]
Hi, 

Can you tell me what is the image height and width + the actual icon size and the border radius of the icon please ?
![Plank Icon](https://user-images.githubusercontent.com/61543256/141276212-9da40098-118d-4e54-8175-5a0583f0d825.png)
![Desk Icon](https://user-images.githubusercontent.com/61543256/141276215-69ed8366-55ef-4102-aaae-20982e1512c5.png)

**Comment by vinceliuice** [comment]
You csn check this: https://github.com/vinceliuice/WhiteSur-icon-theme/tree/master/templates

**Comment by Wilfried-1** [comment]
> You csn check this: https://github.com/vinceliuice/WhiteSur-icon-theme/tree/master/templates

Thanx for the quick answer :)
