### ISSUE TITLE
希望能添加企业微信的图标

### ISSUE THREAD

**Issue by sanwanliu** [vinceliuice/WhiteSur-icon-theme#146]
大佬，非常喜欢你制作的图标，希望能添加企业微信的图标，包名是com.qq.weixin.work.deepin，谢谢

**Comment by vinceliuice** [comment]
企业微信有Linux版了？

**Comment by sanwanliu** [comment]
是deepin wine版本，我一直在用，不过最近维护者没有更新，需要按评论区安装https://aur.archlinux.org/packages/com.qq.weixin.work.deepin

**Comment by vinceliuice** [comment]
好的，我会添加这个图标的
