### ISSUE TITLE
🐛: Distributor logo does not seem to work

### ISSUE THREAD

**Issue by joe733** [vinceliuice/WhiteSur-icon-theme#16]
First off thanks a lot.. I admire your artwork. 

I added elementary os logo from your wonderful Tela-Circle theme. But do I need to add something to `index.theme` to make this work?

![Screenshot from 2020-11-01 13-01-43](https://user-images.githubusercontent.com/38415384/97797529-e2e55900-1c43-11eb-8e05-357b896d982e.png)

The brightness indicator too, shows an invalid icon... how can I fix it?

**Comment by VentGrey** [comment]
This also happens in pop!  :cat:
