### ISSUE TITLE
ICONS MISSING ON FEDORA 33 KDE PLASMA

### ISSUE THREAD

**Issue by gesangtome** [vinceliuice/WhiteSur-icon-theme#17]
Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/WhiteSur/actions/16/image-missing.svg: Unrecognized image file format (gdk-pixbuf-error-quark, 3)
Bail out! Gtk:ERROR:gtkiconhelper.c:494:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /usr/share/icons/WhiteSur/actions/16/image-missing.svg: Unrecognized image file format (gdk-pixbuf-error-quark, 3)

Some system ICONS appear blank.

**Comment by vinceliuice** [comment]
I'll fix this!

**Comment by gesangtome** [comment]
> I'll fix this!

excited！
