### ISSUE TITLE
[Low Priority] VPN icon

### ISSUE THREAD

**Issue by caike08** [vinceliuice/WhiteSur-icon-theme#181]
Hello, 

First of all, thank you for the great work done with the icons. I use both Colloid and WhiteSur icon themes from you.

But I noticed something that bugged me a little. While using WhiteSur icon theme, after connecting to the VPN, I only see the icon without the key inside it. But I do see the key icon if the VPN is turned off.

![image](https://user-images.githubusercontent.com/4422230/177818496-b34c1413-e138-4908-af6a-6aa67cc32e30.png)

![image](https://user-images.githubusercontent.com/4422230/177818469-92d0e6e7-8c26-466d-9cea-a31c29a32a54.png)

![image](https://user-images.githubusercontent.com/4422230/177818371-1c1d97aa-1805-4edd-bdda-5ab0496c6b58.png)

Is this the expected behavior for this icon? I thought it'd have the same idea as the one from Colloid icon theme.

 
![image](https://user-images.githubusercontent.com/4422230/177818731-7bda62ce-0a01-4537-ada3-05e158df4013.png)

**Comment by vinceliuice** [comment]
Fixed
