### ISSUE TITLE
Color picker (Eyedropper) loupe is opaque

### ISSUE THREAD

**Issue by seanleavy** [vinceliuice/WhiteSur-icon-theme#190]
Hi. the color picker icon loupe is opaque when using the WhiteSur icon theme.

The expected behaviour is that the underlying color inside the loupe is vibible within the icon.

See the attached video for a demo.

Application tested: 
**Color Picker** (flatpak)
**flatpak ref**: ` nl.hjdskes.gcolor3`

I also tested with some non-flatpak apps to eliminate that possibility, still the same issue;

Fedora 36
Gnome 42.3
Wayland session

https://user-images.githubusercontent.com/2906363/182615093-6a7084ad-0c05-47de-89b8-c327f25523eb.mp4

**Comment by vinceliuice** [comment]
Fixed now
