### ISSUE TITLE
图标不全

### ISSUE THREAD

**Issue by LingBomanbui** [vinceliuice/WhiteSur-icon-theme#195]
我在使用whiteSur-icon-theme的时候，安装完成但是有大概一半的图标是不显示的，并且不会使用使用系统自带图标去替换，而是直接显示透明的一片空白，我的系统环境是kali2022.2 kde plasma : 5.25.3 kde : 5.96.0 
![image](https://user-images.githubusercontent.com/92626586/187339598-b78503ec-43c5-4138-ac75-7fb399c98498.png)
如果您有时间的话，恳请您能解决我的问题

**Comment by vinceliuice** [comment]
重新安装一下，没安装成功

**Comment by vinceliuice** [comment]
下载的时候下载：https://github.com/vinceliuice/WhiteSur-icon-theme/archive/refs/tags/2022-08-30.tar.gz

**Comment by LingBomanbui** [comment]
谢谢带佬，根据你给出的方法完美解决了这个问题！

**Comment by LingBomanbui** [comment]
这里面是没有jetbrains系的图标吗

**Comment by vinceliuice** [comment]
这个系列软件不使用第三方图标，你需要自己修改启动器
