### ISSUE TITLE
Icon Request: Pop OS logo + launcher icons

### ISSUE THREAD

**Issue by nbycoder** [vinceliuice/WhiteSur-icon-theme#198]
I have noticed a few icons missing (specifically the new window icon) in the launcher, and in the about section in settings. I have tried adding my own according to the original pop os theme, but no luck. anyway, i attached screenshots showing how it looks with WhiteSur vs the Pop Theme.
![Captura de ecrã de 2022-09-24 16-30-11](https://user-images.githubusercontent.com/90400844/192106283-3fdeedb5-f891-4c49-a5ff-88840732cbf9.png)
![Captura de ecrã de 2022-09-24 16-30-38](https://user-images.githubusercontent.com/90400844/192106288-7ddbf9c4-ebe8-417c-ab67-c886251161c0.png)
![image](https://user-images.githubusercontent.com/90400844/192106319-24e08225-a4f0-450a-b5b8-a8f5566a9307.png)
![image](https://user-images.githubusercontent.com/90400844/192106337-9f636b48-461a-4de9-a860-d92c71e77246.png)

**Comment by vinceliuice** [comment]
Fixed
