### ISSUE TITLE
Fix Trash Icon In WhiteSur Dark

### ISSUE THREAD

**Issue by Shikamaru30** [vinceliuice/WhiteSur-icon-theme#211]
It's been bugging me that the Trash icon in WhiteSur Dark is the light mode version of the icon rather than the dark mode version. I'd appreaciate a fix for this whenever possible.

**Comment by prstephens** [comment]
Guess we are being ignored. I raised a new issue and again, fallen on deaf ears. Its such a small thing but makes the whole theme complete. Lets hope Vince is listening....
