### ISSUE TITLE
-r / -u is an unrecognized installation option

### ISSUE THREAD

**Issue by Konglomneshued** [vinceliuice/WhiteSur-icon-theme#212]
![Screenshot from 2022-12-23 12-22-40](https://user-images.githubusercontent.com/94726665/209406694-145b8ab0-5ddb-4509-8011-8c12392dd9a7.png)

![image](https://user-images.githubusercontent.com/94726665/209406810-1101602f-b1af-47fb-b688-bfa7959b9183.png)

**Comment by vinceliuice** [comment]
Download from master

**Comment by vinceliuice** [comment]
Or download the last release
