### ISSUE TITLE
All color folders get included in each color theme

### ISSUE THREAD

**Issue by harmin-parra** [vinceliuice/WhiteSur-icon-theme#214]
After installing the themes (WhiteSur Yellow, Green, Red, etc), I realized that all folder colors get present in each color theme.

Why ?

![Screenshot from 2023-01-12 23-47-17](https://user-images.githubusercontent.com/16239820/212197989-6bd52a19-3be6-4517-a8ff-41ef2b50663f.png)

**Comment by vinceliuice** [comment]
For plasma desktop, dolphin can change folder's color

**Comment by harmin-parra** [comment]
OK, I see the same behavior also in Gnome based Desktops
