### ISSUE TITLE
Request for Solanum

### ISSUE THREAD

**Issue by Yasso9** [vinceliuice/WhiteSur-icon-theme#223]
Can you add an icon for the solanum app. It is an app that helps using pomodoro for productivity.

Gnome app presentation : https://apps.gnome.org/app/org.gnome.Solanum/
Source code : https://gitlab.gnome.org/World/Solanum
App svg icon : https://gitlab.gnome.org/World/Solanum/-/blob/main/data/icons/org.gnome.Solanum.Source.svg

Thanks a lot (By the way I love the icons !!!)

**Comment by vinceliuice** [comment]
Added
