### ISSUE TITLE
Add exit code to the usage function

### ISSUE THREAD

**Issue by FledPaul** [vinceliuice/WhiteSur-icon-theme#226]
## Description
The usage function in the codebase currently prints out usage instructions when called, but it does not exit the script afterwards. This can lead to unexpected behavior as the script will continue running after the usage instructions have been displayed.

To prevent this issue, it is recommended to add the exit 1 command at the end of the usage function. This will terminate the script after the usage instructions have been printed, ensuring that the script does not continue running with unexpected input.

## Proposed Solution
Add the following line of code at the end of the usage function:
```exit 1```

## Expected Outcome
After the usage function is called, the script will display the usage instructions and exit with a status code of 1, indicating that there was an error. This will prevent the script from running further and potentially causing unintended consequences.

**Comment by samwhelp** [comment]
File: install.sh
the last line: [exit 1](https://github.com/vinceliuice/WhiteSur-icon-theme/blob/master/install.sh#L295)

let [AUR / [whitesur-icon-theme-git](https://aur.archlinux.org/packages/whitesur-icon-theme-git) / [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=whitesur-icon-theme-git#n25)] not complete work.

$ `man bash`

> [EXIT_STATUS](https://man.archlinux.org/man/bash.1.en#EXIT_STATUS)

```
For the shell's purposes, a command which exits with a zero exit status has succeeded. An exit status of zero indicates success. A non-zero exit status indicates failure.
```

$ man sh

>  [EXIT_STATUS](https://man.archlinux.org/man/bash.1.en#EXIT_STATUS)
