### ISSUE TITLE
[Request] New Icons

### ISSUE THREAD

**Issue by btd1337** [vinceliuice/WhiteSur-icon-theme#24]
Most icons below can be found in: https://macosicons.com/

Hint convert ICNS to SVG: https://iconverticons.com/

- [ ] **Alacritty**
Comment=A cross-platform, GPU enhanced terminal emulator
Icon=Alacritty
[Icon Link](https://storage.googleapis.com/download/storage/v1/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2F1604764667778_Alacritty.png?generation=1604778443898727&alt=media)

- [ ] **Anki**
Comment=An intelligent spaced-repetition memory training program
Icon=anki
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FAnki.png?alt=media&token=dd0826d1-0faf-46c1-bab9-e548dc58083f)

- [ ] **balenaEtcher**
Comment=Flash OS images to SD cards and USB drives, safely and easily.
Icon=balena-etcher-electron
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FbalenaEtcher.png?alt=media&token=71771f62-67f4-452a-a8bc-5421f38f78b2)

- [ ] **Code::Blocks IDE**
Comment=Configurable and extensible IDE
Icon=codeblocks
[Icon Link](https://img.utdstc.com/icons/code-blocks.png:200)

- [ ] **Taxi**
Comment=Transfer local and remotes files
Icon=com.github.alecaddd.taxi
[Icon Link](https://github.com/Alecaddd/taxi/blob/master/data/icons/128.svg)

- [ ] **Minder**
Comment=Create, develop and visualize your ideas
Icon=com.github.phase1geo.minder
[Icon Link](https://github.com/phase1geo/Minder/blob/master/data/icons/128/com.github.phase1geo.minder.svg)

- [ ] **Haguichi**
Comment=Join and create local networks over the Internet
Icon=com.github.ztefn.haguichi
[Icon Link](https://github.com/ztefn/haguichi/blob/master/data/icons/hicolor/scalable/apps/haguichi.svg)

- [ ] **Electron 9**
Icon=electron9
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FElectron.png?alt=media&token=264bd9e8-1f13-42d0-afca-1f4954ef7705)

- [ ] **FileZilla**
Comment=Download and upload files via FTP, FTPS and SFTP
Icon=filezilla
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FFilezilla.png?alt=media&token=429d5cc0-35c3-4d5b-a0c9-2fc60df63c19)

- [ ] **Network Tools**
Comment=View information about your network
Icon=gnome-nettool
[Icon Link]()

- [ ] **Thunderbolt**
Comment=Manage Thunderbolt devices
Icon=thunderbolt
[Icon Link]()

- [ ] **Go For It!**
Comment=A stylish to-do list with built-in productivity timer
Icon=go-for-it
[Icon Link](https://github.com/JMoerman/Go-For-It/blob/master/data/icons/128x128/apps/go-for-it.svg)

- [ ] **Package Log**
Comment=View past package management tasks
Icon=gpk-log
[Icon Link]()

- [ ] **Firewall Configuration**
Comment=An easy way to configure your firewall
Icon=gufw
[Icon Link](https://github.com/costales/gufw/blob/master/data/icons/scalable/apps/gufw.svg)

- [ ] **OpenJDK Java 11**
Comment=OpenJDK Java 11
Icon=java11-openjdk
[Icon Link]()

- [ ] **OpenJDK Java 14**
Comment=OpenJDK Java 14
Icon=java14-openjdk
[Icon Link]()

- [ ] **Micro**
Comment=Edit text files in a terminal
Icon=micro
[Icon Link](https://github.com/zyedidia/micro/blob/master/assets/micro-logo-mark.svg)

- [ ] **MongoDB Compass**
Comment=The MongoDB GUI
Icon=mongodb-compass
[Icon Link](https://github.com/mongodb-js/compass/blob/master/src/app/images/linux/mongodb-compass.png)

- [ ] **PlayOnLinux**
Comment=Front-end application for the wine
Icon=playonlinux
[Icon Link](https://avatars1.githubusercontent.com/u/373652?s=200&v=4)

- [ ] **Robo 3T**
Comment=Shell-centric MongoDB management tool
Icon=robo3t
[Icon Link](https://raw.githubusercontent.com/Studio3T/robomongo/master/src/robomongo/gui/resources/icons/logo-256x256.png)

- [ ] **Typora**
Icon=typora
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FTypora.png?alt=media&token=c304ee8a-18c6-4196-9790-c4eba734c870)

- [ ] **pcloud**
Comment=pCloud Drive Client built using electron and node.js. Distributed with AppImage.
Icon=appimagekit-pcloud
[Icon Link](https://firebasestorage.googleapis.com/v0/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2FpCloud_Drive.png?alt=media&token=d3cf97c3-e881-4f92-bfaf-afa11995b070)

- [ ] **0 A.D.**
Comment=A real-time strategy game of ancient warfare
Icon=0ad
[Icon Link](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/blob/master/icons/0_AD.icns)

> Generated by https://github.com/btd1337/icons-missing-script

**Comment by vinceliuice** [comment]
No problem!

**Comment by ducviet00** [comment]
I suggest adding Viber icon:
https://storage.googleapis.com/download/storage/v1/b/macos-icons.appspot.com/o/icons_approved%2Fpng%2F1605375180046_Viber_iOS.png?generation=1605436842694024&alt=media

**Comment by sergiosassi** [comment]
Hi! I miss the icons:

**Comment by vinceliuice** [comment]
No problem!

**Comment by thesauravkarmakar** [comment]
Update IntelliJ products icon to these as the default ones aren't exactly similar to the ones in macOS 
- PyCharm CE  [Icon Link](https://media.macosicons.com/parse/files/macOSicons/57853a4b26ff45771a52d9f3a80b7892_IntelliJ_PyCharm.png) 
- IntelliJ CE [Icon Link](https://media.macosicons.com/parse/files/macOSicons/b1f455c739aa9a156975f29e4504e56f_IntelliJ.icns)
