### ISSUE TITLE
[bug] Non-apple icon for nautilus

### ISSUE THREAD

**Issue by null-von-sushi** [vinceliuice/WhiteSur-icon-theme#242]
#30 was closed as an alternative icon theme has been implemented, however the apple's vivec looking face icon is still shown for nautilus in GNOME (the monochrome icon in the top panel).
![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/13616397/59efbeb0-372f-42e8-90a0-a53a3cc92984)

**Comment by vinceliuice** [comment]
Fixed now

**Comment by null-von-sushi** [comment]
Thank you
