### ISSUE TITLE
new icons request

### ISSUE THREAD

**Issue by saltedcoffii** [vinceliuice/WhiteSur-icon-theme#25]
Please make icons for these apps, thank you!!
giara (org.gabmus.giara) a GTK+ reddit client
gtkcord3, a GTK+ discord client (the discord logo but chromatic rainbow would likely suffice) (https://github.com/diamondburned/gtkcord3)
lightcord, a modified discord client (the discord logo but red would likely suffice) (https://github.com/lightcord/lightcord)
anbox, and if you can, the google play store within
"manage printing", the cups GUI
dosbox

thank you :)

**Comment by vinceliuice** [comment]
Added
