### ISSUE TITLE
Deffective "RetroArch" icon

### ISSUE THREAD

**Issue by mcnum1** [vinceliuice/WhiteSur-icon-theme#267]
![Снимок экрана от 2024-02-21 21-18-25](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/148763220/b9e3e46a-b325-4e56-9940-6ccc93b42d17)

**Comment by a-irsyad** [comment]
Looks good to me. Can you explain what you mean? https://apps.apple.com/us/app/retroarch/id6499539433

**Comment by vinceliuice** [comment]
Fixed
