### ISSUE TITLE
Error Icons

### ISSUE THREAD

**Issue by emmyvinte** [vinceliuice/WhiteSur-icon-theme#268]
Name: Mousai (flathub), nvtop (aur), Tixati (aur)
Links: https://apps.gnome.org/pt-BR/Mousai/ , https://github.com/Syllo/nvtop , https://www.tixati.com/
![mousai](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/117837570/03834bcf-4f72-43c5-9d0c-e891103deb47)
![nvtop](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/117837570/c0fd759a-b97e-4794-a774-57cae8131b13)
![tixati](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/117837570/e9268bc2-d2ad-4a03-b956-5d3d1bcbbe8e)

**Comment by Mibea** [comment]
![Schermafdruk van 2024-03-01 21-54-30](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/96521634/c8ddef67-5bd3-465e-8d16-075858eada10)

**Comment by emmyvinte** [comment]
that's very good
