### ISSUE TITLE
Spotify Icon not working

### ISSUE THREAD

**Issue by helmrich** [vinceliuice/WhiteSur-icon-theme#27]
Hi there,

I'm running Fedora 33 and installed Spotify via Flatpak and it's using the default icon instead of the icon theme's icon. All other icons appear to work just fine. Is there any way to fix this? Maybe it has to do something with the icon name, as the value in Spotify's .desktop file is `Icon=com.spotify.Client` whereas the icon is called `spotify-client.svg`.

Best regards and thank you for your hard work!

**Comment by vinceliuice** [comment]
I'll fix this
