### ISSUE TITLE
All "WhiteSur-color-dark" themes do not change the color of folders

### ISSUE THREAD

**Issue by mcnum1** [vinceliuice/WhiteSur-icon-theme#271]
**Describe the bug**
All "WhiteSur-*color*-dark" themes do not change the color of folders, but the "WhiteSur-*color*" and "WhiteSur-*color*-light" themes work correctly.

**Screenshots**
![Снимок экрана от 2024-03-06 02-35-29](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/148763220/9babe684-8d4f-4a74-bee4-c0c64c6c0249)
![Снимок экрана от 2024-03-06 02-35-36](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/148763220/0931379e-8217-4f15-b990-2285e540c9d9)

**Comment by Dejweed** [comment]
+1

When installing all colors, dark ones use default blue folders. @vinceliuice 

![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/65261588/030a8522-d861-479a-981e-846856c8e48d)

**Comment by Dejweed** [comment]
But when choosing red, the folders should be red, like they are with WhiteSur-light. With WhiteSur-dark, they are always blue, no matter the accent color. I think the install script needs to be fixed.

**Comment by vinceliuice** [comment]
You are right, there is a issue about install script

**Comment by vinceliuice** [comment]
Fixed now
