### ISSUE TITLE
Icons only partially showing when installing from Terminal

### ISSUE THREAD

**Issue by david03130** [vinceliuice/WhiteSur-icon-theme#278]
**Describe the bug**
When I install the icons from the KDE Store they work correctly, but since I want the alternative version, I have to install them using the script. When I do so, half of the icons are just blank.

**To Reproduce**
1. Open terminal in source code directory.
2. Write `.\install.sh -a` (the error also happens with the normal version of the icons)

**Expected behavior**
To see the alternative icons correctly.

**Screenshots**
None of these icons are displaying correctly (Plank Dock)
![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/99992909/9b757de7-6599-49f8-9883-b9ca6069482e)

Half of the icons in System Settings are just blank
![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/99992909/eb1dab6e-20dc-4622-8b8d-4b2ceba9c473)

Another example in Dolphin.
![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/99992909/1ca88514-73dd-4fa5-90c7-d664b4b52f08)

**Desktop (please complete the following information):**
 - OS: Fedora 39, KDE 5.27.11 (Framework 5.115.0), QT 5.15.12, Graphics Platform: X11

**Additional context**
I have used these icons before in Fedora GNOME and looked amazing.

**Comment by vinceliuice** [comment]
Run `./install.sh` again

**Comment by david03130** [comment]
Downloaded from latest commit. Still nothing.

![Screenshot_20240407_140308](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/99992909/50c4e2de-2f22-4730-bf59-acac786af5af)

**Comment by vinceliuice** [comment]
Download this: https://github.com/vinceliuice/WhiteSur-icon-theme/archive/refs/tags/2024.04.08.tar.gz
and try again, there must be something issue with the link files, maybe zip file cause it, linux support tar.gz better

**Comment by david03130** [comment]
**That worked!** Didn't even cross my mine that extraction could be causing the issue.

Thanks for the fast response and for the amazing work with the icon theme! :)
