### ISSUE TITLE
theme doesnt change hover color and folder colors

### ISSUE THREAD

**Issue by stigman9393** [vinceliuice/WhiteSur-icon-theme#281]
Hello, i dont know so much about themming in gnome with libadwaita but i found a bug like on screen, i cant change folder colors and i cant change that color on hover which is orange and i set it up to purple. Can you also make a labels or instruction which version of theme is for which version of gnome?

![Zrzut ekranu z 2024-04-14 19-56-09](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/147590841/8ca3666c-21ea-436f-8aed-32aef9b504c4)
![Zrzut ekranu z 2024-04-14 20-01-16](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/147590841/97cfa59b-e31d-4562-80ea-378c71dc7551)

 - OS: Debian 12
 - App: Nautilus
 - Version: Gnome 43

**Comment by vinceliuice** [comment]
Fixed now
