### ISSUE TITLE
Very thin icons in Remmina on 2.5k 27" monitor

### ISSUE THREAD

**Issue by iAweX** [vinceliuice/WhiteSur-icon-theme#292]
**Describe the bug**
Very thin icons in Remmina on 2.5k 27" monitor compared to default gnome icons

WhiteSur icons

![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/50710418/21068a86-a769-45fe-a6fe-b6b97522dd3b)

Gnome icons

![image](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/50710418/cb40e8cf-cf26-49db-8fa4-54c93b89b89f)

**Desktop (please complete the following information):**
 - OS: Debian 12.5
 - App Remmina
 - Version 1.4.35 (git 2a455ea)

**Additional context**

**Comment by kernelb00t** [comment]
This won't fix, because of the nature of how the icons are being displayed: those are publicly declared, and if they are made bolder so they look good in Remmina, they will look too strong in other apps. That's the tradeoff that should be beared as this is not Apple with not equivalent resources 😉
