### ISSUE TITLE
[Icon request] Anytype

### ISSUE THREAD

**Issue by Xuaolu** [vinceliuice/WhiteSur-icon-theme#297]
1. App name: Anytype
2. App Webside: https://anytype.io/
3. App icon name: anytype
<img width="200" alt="326997730-5c60a3f8-9744-4bd8-ac0f-41558323114d" src="https://github.com/vinceliuice/WhiteSur-icon-theme/assets/119270979/a4bf510f-8d55-444b-b7b3-0da0f90ce3dc">

**Comment by Mibea** [comment]
https://github.com/vinceliuice/WhiteSur-icon-theme/pull/298/files#diff-b42e0e0bbc4bc0e62875457eb1434ffb0a0a27a6622c49bfa31fd15ec599d0f4
