### ISSUE TITLE
[Request] 'Non-apple' alternatives

### ISSUE THREAD

**Issue by brneor** [vinceliuice/WhiteSur-icon-theme#30]
I love the looks of the icons, but I don't like my system looking like a macOS ripoff. Would be possible to have alternatives to macOS icons like Finder icon for Files and AppStore for Software?

**Comment by MischievousTomato** [comment]
Exactly this. It's what keeps me from using this theme!

**Comment by dada513** [comment]
Same. It looks awesome but the apple icons threw me off
