### ISSUE TITLE
[Plasma 6] Some icons does not shown, even on 4.08, 4.22 update of WhiteSur icon packs

### ISSUE THREAD

**Issue by Ramen-LadyHKG** [vinceliuice/WhiteSur-icon-theme#300]
**Describe the bug**
I was using the 2023.07.03 icon pack when Plasma 6 was updated, some icons was missing.
Then I heard WhiteSur has updated the icon pack, so I installed 4.22. Now almost all KDE applications and some apps, plasma plasmoids icons become blank.

That issue also caused `Firefox` to crash when opening file dialog.

KDE theme- `Whitesur-kde` was used.

**To Reproduce**
1. Update icon pack using the `install.sh` from `2024.04.22`, and `--bold` option was used, I also tried `--theme orange`.
2. A lot of icons was not loaded (`Terminal`, `Qalculate!`, `Dolphin`, `Input Method`, `Battery` etc....)
3. There are errors in terminal says 
```
May 27 12:39:31 SB2-2023M3-A6213 plasmashell[20038]: Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/curie/.local/share/icons/WhiteSur-orange-dark/actions@2x/16/image-missing.svg: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
May 27 12:39:31 SB2-2023M3-A6213 plasmashell[20038]: Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/curie/.local/share/icons/WhiteSur-orange-dark/actions@2x/16/image-missing.svg: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
May 27 12:41:22 SB2-2023M3-A6213 plasmashell[22164]: Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/curie/.local/share/icons/WhiteSur-orange-dark/actions@2x/16/image-missing.svg: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
May 27 12:41:22 SB2-2023M3-A6213 plasmashell[22164]: Bail out! Gtk:ERROR:../gtk/gtk/gtkiconhelper.c:495:ensure_surface_for_gicon: assertion failed (error == NULL): Failed to load /home/curie/.local/share/icons/WhiteSur-orange-dark/actions@2x/16/image-missing.svg: Unrecognised image file format (gdk-pixbuf-error-quark, 3)
May 27 13:00:27 SB2-2023M3-A6213 systemsettings[19004]: qt.svg: Cannot read file '/home/curie/.local/share/icons/WhiteSur-light/apps/scalable/system-run.svg', because: Start tag expected. (line 1)

4. In `Firefox`/`Floorp` when filedialog is opened, it instantly crashed `Firefox`
5. Revert back to `Breeze-dark`, everything becomes normally.
```
**Expected behavior**
All non-modified icons should show.
Breeze-Dark: When WhiteSur-icon is not used

> ![Screenshot_A6213 1 _(2024-May-27)_ 01,26,19](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/123364699/7430e7e2-2015-4a8e-aae2-dbf5d915de3d)

**Screenshots**

### These are the errors shown in `journalctl -fe`
> ![Screenshot_A6213 1 _(2024-May-27)_ 12,41,03](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/123364699/f89ef9e7-97d3-4001-ad13-cfdd31733855)

WhiteSur-orange-Dark
> ![Screenshot_A6213 1 _(2024-May-27)_ 01,14,24](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/123364699/42eb1cc8-c870-4099-b313-c1d94f569b6d)

WhiteSur-Dark
> ![Screenshot_A6213 1 _(2024-May-27)_ 01,16,18](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/123364699/9551d06a-e874-4148-a4ba-2f603877efc2)

**Desktop (please complete the following information):**
 - OS: Arch Linux (`6.8.8-arch1-1-surface (64-bit)`)
 - Plasma 6: `6.0.5`
 - Version: WhiteSur-icon-theme-2024-04-22

**Comment by vinceliuice** [comment]
Download the tar.gz file do not download the zip file: https://github.com/vinceliuice/WhiteSur-icon-theme/archive/refs/tags/2024-05-28.tar.gz

**Comment by vinceliuice** [comment]
zip file not support linux link files

**Comment by Ramen-LadyHKG** [comment]
> zip file not support linux link files

Ohohoh, no wonder


Thank you so much
