### ISSUE TITLE
[Icon request] [Super Productivity] 

### ISSUE THREAD

**Issue by 20CCAA07** [vinceliuice/WhiteSur-icon-theme#307]
Thanks for this great Icon Theme.

May I ask you to please add a fitting icon for Super Productivity?

**Tell me things about the app or icon**
1. App name: Super Productivity
2. App Webside: [Super Productivity](https://super-productivity.com)
3. App icon name: superProductivity

**Additional context**
Icon example from the Appstore:
![Icon](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/86972413/58768551-e975-497b-862a-162a208356ec)

Thank you!

**Comment by Mibea** [comment]
![afbeelding](https://github.com/vinceliuice/WhiteSur-icon-theme/assets/96521634/42ccc759-9985-4cf8-93cf-fe5e25a99b23)
