### ISSUE TITLE
plasma 6 status-panel (sound, network etc.): does not change appearance

### ISSUE THREAD

**Issue by slynobody** [vinceliuice/WhiteSur-icon-theme#315]
**Describe the bug**
After upgrading to plasma 6 the status-panel (sound, network etc.) does not change appearance anymore (when changing plasma-style). Are there changes necessary to the code you did not do? Or is this a problem of my distro (debian)?

**To Reproduce**
1. upgrade plasma 5 to plasma 6
2. change plasma-style to one of your themes (f.e. Lavanda-Dark or Layan)
3. take a look at the status-panel (no changes)

**Expected behavior**
changed icons afterwards.

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: experimental / plasma 6

**Comment by vinceliuice** [comment]
This is not a bug, this is a update of plasma 6.0 desktop, since plamsa 6.0 it droped use icons in plasma theme, instead it'll use icon theme icons

**Comment by vinceliuice** [comment]
You want change those icons you need change your icon theme

**Comment by slynobody** [comment]
and you try to change the icon themes now to accomplish this on plasma 6+?
