### ISSUE TITLE
Suggestion: Change video file icon for alt icons

### ISSUE THREAD

**Issue by Zumux** [vinceliuice/WhiteSur-icon-theme#325]
Video files in nautilus use an icon with the quicktime logo even with the alt version. I propose this is changed to something different for the alt version.

**Comment by buufmax** [comment]
+1 I'd like if we had a standard video icon, but with relevant extension formats ie mp4, mkv, wmv etc... Something similar to the images JPG, PNG would be very welcome this changes if it would happen.
