### ISSUE TITLE
gtk-update-icon-cache: The generated cache was invalid.

### ISSUE THREAD

**Issue by Neo-29** [vinceliuice/WhiteSur-icon-theme#326]
Using the install script, on the last pull here's what I've got on gnome 47 archlinux
All was ok a few days ago

`gtk-update-icon-cache: The generated cache was invalid`

**Comment by crocofied** [comment]
Same here on Linux Mint 22

**Comment by crocofied** [comment]
Temp Walkaround is to install an older release, but the current pull does not work
`git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git --branch 2024-09-07`
