### ISSUE TITLE
Wrong Apply icon on KDE Settings - Date & Time

### ISSUE THREAD

**Issue by buufmax** [vinceliuice/WhiteSur-icon-theme#338]
There is a wrong Apply icon on KDE Settings - Date & Time.

`systemsettings kcm_clock`

![Screenshot_20241101_075255](https://github.com/user-attachments/assets/67a08126-51f6-4e5d-a9ad-e5fa03594ae8)

```
Operating System: openSUSE Tumbleweed 20241030
KDE Plasma Version: 6.2.2
KDE Frameworks Version: 6.7.0
Qt Version: 6.8.0
Graphics Platform: Wayland
---
WhiteSur-icon-theme (master)
```

**Comment by vinceliuice** [comment]
What is wrong ?

**Comment by buufmax** [comment]
Button Apply on this setting don't have 🗸 check mark.
