### ISSUE TITLE
Wrong icon for *.tar.bz2

### ISSUE THREAD

**Issue by buufmax** [vinceliuice/WhiteSur-icon-theme#340]
Archive **tar.bz2** show a wrong text editor instead of archive icon.

![Screenshot_20241102_075702](https://github.com/user-attachments/assets/8d8b71b7-22ab-4d45-afd9-9528ef2ec5e8)

`WhiteSur-icon-theme (master)`

**Comment by vinceliuice** [comment]
This tar.bz2 you have got errors, check it's size, not a theme issue

**Comment by buufmax** [comment]
File "LosslessCut-linux-x64.tar.bz2" downloaded here, extraction was successful.
https://github.com/mifi/lossless-cut/releases

```
Type: Tar archive (bzip2-compressed)
Content: Bzip2 archive
Filesize: 145.5 MiB (152,551,117)
```

**Comment by vinceliuice** [comment]
![Screenshot From 2024-11-02 16-37-40](https://github.com/user-attachments/assets/0029722a-f1da-4428-959a-5ed226c5251a)

**Comment by vinceliuice** [comment]
It's not a theme issue

**Comment by vinceliuice** [comment]
Right click on your tar.bz2 file click `Properties` to check file type

**Comment by vinceliuice** [comment]
![Screenshot From 2024-11-02 16-41-05](https://github.com/user-attachments/assets/bf1bafc2-8fb1-4f38-99ae-85f0ea88e41c)

**Comment by vinceliuice** [comment]
Check if it's `bzip-compressed`, if not then will not show the right icon

**Comment by vinceliuice** [comment]
Maybe 
1. The file was not completely downloaded
2. Icon theme not completely installed

**Comment by buufmax** [comment]
I downloaded it several times to make sure it downloads all right. I use browser Google Chrome - Unstable Version 132.0.6793.2 (Official Build) dev (64-bit).

Icon theme installed using this alias from .bashrc
`alias whitesur="git clone https://github.com/vinceliuice/WhiteSur-icon-theme.git && $HOME/WhiteSur-icon-theme/install.sh -d $HOME/.local/share/icons -n WhiteSur -a -b -t grey && rm -rf $HOME/WhiteSur-icon-theme"`
By terminal/konsole i just write whitesur to install from git (master) release.

The WhiteSur-icon-theme package downloads and installed properly after using this procedure for a long time.

I hit several time F5 for refresh.

This is right click Properties from WhiteSur
![Screenshot_20241102_105916](https://github.com/user-attachments/assets/df89ff3b-1f8f-44bf-90f5-f3dc5d91df5a)
This is right click Properties from Breeze
![Screenshot_20241102_110146](https://github.com/user-attachments/assets/85155033-291d-46b3-8c65-ee325f4d31c5)

```
'bzip2' is already installed.
No update candidate for 'bzip2-1.0.8-5.10.x86_64'. The highest available version is already installed.
```

I'm finding that when i close the file manager (Dolphin) and open it again, it tries to go to the Archive icon, but immediately replaced by the text editor icon. Here is the video demonstration.
[Screencast_20241102_111158.webm](https://github.com/user-attachments/assets/60476251-0abc-414f-8a0a-1bb9ed0b6766)

**Comment by vinceliuice** [comment]
nautilus and nemo looks fine, only dolphin have this issue, I'm looking for the reason

**Comment by vinceliuice** [comment]
I think that maybe a dolphin issue, It can not add `text-x-preview.svg` icon, or tar.bz2 files will show `text-x-preview` icon,
I test Papirus and Numix icon theme, all have this issue

**Comment by vinceliuice** [comment]
Fixed now
