### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by btd1337** [vinceliuice/WhiteSur-icon-theme#4]
- [ ] **0 A.D.**
Comment=A real-time strategy game of ancient warfare
Icon=0ad
[Icon Link](https://a.fsdn.com/allura/p/zero-ad/icon?1563751270)

- [ ] **Android Studio**
Comment=The official Android IDE
Icon=android-studio
[Icon Link](https://pt.wikipedia.org/wiki/Ficheiro:Android_Studio_icon.svg)

- [ ] **DotFonts**
Comment=Find beautiful fonts and easy install
Icon=com.github.aimproxy.dotfonts
[Icon Link](https://github.com/aimproxy/dotfonts/blob/master/data/icons/128/com.github.aimproxy.dotfonts.svg)

- [ ] **Akira**
Comment=The Linux Design Tool
Icon=com.github.akiraux.akira
[Icon Link](https://github.com/akiraux/Akira/blob/master/data/icons/128x128/com.github.akiraux.akira.svg)

- [ ] **Planner**
Comment=Never worry about forgetting things again
Icon=com.github.alainm23.planner
[Icon Link](https://github.com/alainm23/planner/blob/master/data/icons/128/com.github.alainm23.planner.svg)

- [ ] **Sequeler**
Comment=Friendly SQL Client
Icon=com.github.alecaddd.sequeler
[Icon Link](https://github.com/Alecaddd/sequeler/blob/master/data/assets/icons/128x128/com.github.alecaddd.sequeler.svg)

- [ ] **Cipher**
Comment=Encode and decode text
Icon=com.github.arshubham.cipher
[Icon Link](https://github.com/arshubham/cipher/blob/master/data/images/icons/128/com.github.arshubham.cipher.svg)

- [ ] **Hash It**
Comment=Generate and verify file hashes
Icon=com.github.artemanufrij.hashit
[Icon Link](https://github.com/artemanufrij/hashit/blob/master/data/icons/64/com.github.artemanufrij.hashit.svg)

- [ ] **Regex Tester**
Comment=Testing regular expressions
Icon=com.github.artemanufrij.regextester
[Icon Link](https://github.com/artemanufrij/regextester/blob/master/data/icons/64/com.github.artemanufrij.regextester.svg)

- [ ] **Fondo**
Comment=Find the most beautiful wallpapers
Icon=com.github.calo001.fondo
[Icon Link](https://github.com/calo001/fondo/blob/master/data/images/icons/128/com.github.calo001.fondo.svg)

- [ ] **Copy Paste Grab**
Comment=Download videos from hundreds of websites
Icon=com.github.cryptowyrm.copypastegrab
[Icon Link](https://github.com/cryptowyrm/copypastegrab/blob/master/data/icons/128/com.github.cryptowyrm.copypastegrab.svg)

- [ ] **Agenda**
Comment=Get things done
Icon=com.github.dahenson.agenda
[Icon Link](https://github.com/dahenson/agenda/blob/master/data/icons/128/com.github.dahenson.agenda.svg)

- [ ] **Formatter**
Comment=Format devices
Icon=com.github.djaler.formatter
[Icon Link](https://github.com/Djaler/Formatter/blob/master/data/icons/com.github.djaler.formatter.svg)

- [ ] **Marker**
Comment=A simple markdown editor for GTK+
Icon=com.github.fabiocolacio.marker
[Icon Link](https://github.com/fabiocolacio/Marker/blob/master/data/com.github.fabiocolacio.marker.svg)

- [ ] **Tuner**
Comment=Listen to Radio Stations all over the world
Icon=com.github.louis77.tuner
[Icon Link](https://github.com/louis77/tuner/blob/master/data/icons/128/com.github.louis77.tuner.svg)

- [ ] **JS Test**
Comment=Test some JavaScript
Icon=com.github.timecraft.js-test
[Icon Link](https://github.com/timecraft/js-test/blob/master/data/icons/128/com.github.timecraft.js-test.svg)

- [ ] **Haguichi**
Comment=Join and create local networks over the Internet
Icon=com.github.ztefn.haguichi
[Icon Link](https://github.com/ztefn/haguichi/blob/master/data/icons/hicolor/scalable/apps/haguichi.svg)

- [ ] **VidCutter**
Comment=the simplest + fastest video cutter & joiner
Icon=com.ozmartians.VidCutter
[Icon Link](https://github.com/ozmartian/vidcutter/blob/master/data/icons/hicolor/128x128/apps/com.ozmartians.VidCutter.png)

- [ ] **DBeaver Community**
Comment=Universal Database Manager and SQL Client.
Icon=dbeaver
[Icon Link](https://raw.githubusercontent.com/dbeaver/dbeaver/devel/product/standalone/icons/dbeaver.ico)

- [ ] **Eclipse**
Comment=Java Development Environment
Icon=eclipse
[Icon Link](https://user-images.githubusercontent.com/11943860/46922575-7017cf80-cfe1-11e8-845a-0cd198fb546c.png)

- [ ] **Green Recorder**
Comment=Record your desktop easily using a simple GUI
Icon=green-recorder
[Icon Link](https://github.com/foss-project/green-recorder/blob/master/data/green-recorder.png)

- [ ] **Grub Customizer**
Comment=Customize the bootloader (GRUB2 or BURG)
Icon=grub-customizer
[Icon Link](https://github.com/mdeguzis/grub-customizer/blob/master/misc/icons/128x128.png)

- [ ] **HP Device Manager**
Comment=View device status, ink levels and perform maintenance.
Icon=hp_logo
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/hp.svg)

- [ ] **pCloud**
Comment=pCloud Drive Client built using electron and node.js. Distributed with AppImage.
Icon=pcloud
[Icon Link](https://github.com/Bonandry/adwaita-plus/blob/master/Adwaita%2B%2B/apps/scalable/pcloud.svg)

- [ ] **Pomotroid**
Comment=A simple and visually-pleasing Pomodoro timer
Icon=pomotroid
[Icon Link](https://github.com/Splode/pomotroid/blob/master/build/icons/256x256.png)

- [ ] **Popcorn Time**
Comment=Watch Movies and TV Shows instantly
Icon=popcorntime
[Icon Link]()

- [ ] **Spotify**
Icon=spotify-client
[Icon Link]()

- [ ] **StarUML**
Comment=A sophisticated software modeler
Icon=staruml
[Icon Link](https://avatars1.githubusercontent.com/u/7642181?s=200&v=4)

- [ ] **SVG Cleaner**
Comment=Batch, tunable SVG cleaning program
Icon=svgcleaner
[Icon Link](https://github.com/RazrFalcon/svgcleaner-gui/blob/master/icons/svgcleaner.ico)

- [ ] **Microsoft Teams - Preview**
Comment=Microsoft Teams for Linux is your chat-centered workspace in Office 365.
Icon=teams
[Icon Link](https://commons.wikimedia.org/wiki/File:Microsoft_Office_Teams_(2018%E2%80%93present).svg)

- [ ] **Youtube-dl GUI**
Comment=GUI for youtube-dl downloader
Icon=youtube-dl-gui
[Icon Link](https://github.com/MrS0m30n3/youtube-dl-gui/blob/master/youtube_dl_gui/data/icons/hicolor/128x128/apps/youtube-dl-gui.png)

**Comment by vinceliuice** [comment]
No problem!

**Comment by rayonnunes** [comment]
Also if I could suggest an Icon for Slack
[icon link](https://brandfolder.com/slack/logos)

**Comment by vinceliuice** [comment]
Added now
