### ISSUE TITLE
Tor Browser has a Safari icon

### ISSUE THREAD

**Issue by amadejpapez** [vinceliuice/WhiteSur-icon-theme#44]
Hi! Thank you for this project! Recent changes made Tor Browser to have a Safari icon. I really liked the Tor Browser icon so can this somehow be changed back?

![image](https://user-images.githubusercontent.com/63184600/109387272-ba732000-7900-11eb-8e47-a01fda5ac30e.jpeg)

**Comment by amadejpapez** [comment]
Added a custom icon for Tor Browser to solve this

**Comment by vinceliuice** [comment]
I'll update this

**Comment by Froggy232** [comment]
Hi,
On Archlinux, I still have the purple safari icon. Maybe it's because I use the french version of Tor?
Do you know if it's normal, and how to retrieve the tor icon?
Thanks you a lot!

**Comment by amadejpapez** [comment]
> Hi,
> 
> On Archlinux, I still have the purple safari icon. Maybe it's because I use the french version of Tor?
> 
> Do you know if it's normal, and how to retrieve the tor icon?
> 
> Thanks you a lot!

Hi! I had the same issue but I fixed it by manually downloading the icon and replacing it.

First, I downloaded the icon and then moved it into `/usr/share/pixmaps` folder. Then I went to `/usr/share/applications` and here you will find the file with the Tor browser name, go under `Icon=` value and change it to the icon path. Refresh or log out and see if it worked. :D

**Comment by Froggy232** [comment]
Thanks!
Do you remember where you downloaded it?

**Comment by amadejpapez** [comment]
Search on Google for the Tor icon and there should be some.

**Comment by Froggy232** [comment]
Thanks a lot!

**Comment by amadejpapez** [comment]
No problem! I hope it will work for you too :D

**Comment by Froggy232** [comment]
It haven't unfortunately, but it's not a big deal, thanks for your help!
Have a nice day

**Comment by amadejpapez** [comment]
> It haven't unfortunately, but it's not a big deal, thanks for your help!
> 
> Have a nice day

Really? I am also using Arch, so this *should* work. Did you try to put the whole icon path in the `Icon=` value?

**Comment by Froggy232** [comment]
Yes, with and without the extension, and also only the icon name. I have rebooted many times, and still nothing.
But it's a very old installation, and it's a very dirty one.
It's not a big deal anyway, thanks for your reply!

**Comment by amadejpapez** [comment]
> Yes, with and without the extension, and also only the icon name. I have rebooted many times, and still nothing.
> 
> But it's a very old installation, and it's a very dirty one.
> 
> It's not a big deal anyway, thanks for your reply!
> 
> 

Did you also try like `Icon=/usr/share/pixmaps/image.png`? If this doesn't work, then I really don't know.

**Comment by Froggy232** [comment]
> > Yes, with and without the extension, and also only the icon name. I have rebooted many times, and still nothing.
> > But it's a very old installation, and it's a very dirty one.
> > It's not a big deal anyway, thanks for your reply!
> 
> Did you also try like `Icon=/usr/share/pixmaps/image.png`? If this doesn't work, then I really don't know.

Yes, exactly like that, and it doesn't work.
I suspect I must have a .desktop file somewhere because I had made a lot of modification with alacarte, but it's really not important.

**Comment by amadejpapez** [comment]
Oh okay. Sorry I wasn't able to help!

**Comment by Froggy232** [comment]
Don't be sorry, thanks a lot for your answers!
