### ISSUE TITLE
Icon requests

### ISSUE THREAD

**Issue by jo12bar** [vinceliuice/WhiteSur-icon-theme#5]
Hi! Is it possible to add icons for the following two apps? I'll use the same request style as @btd1337 in issue #4...

| App | `Comment=` | `Icon=` | Link to icon online |
|------|---------------|---------|----------------------|
| __Firefox Developer Edition__ | Browse the World Wide Web | `firefox-developer-edition` | [![Firefox Developer Edition icon link](https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/aurora/content/about-logo.svg)](https://hg.mozilla.org/mozilla-central/raw-file/tip/browser/branding/aurora/content/about-logo.svg) |
| __Kitty__ | A fast, feature full, GPU based terminal emulator | `kitty` | [![Kitty terminal icon link](https://raw.githubusercontent.com/kovidgoyal/kitty/master/logo/kitty.svg)](https://github.com/kovidgoyal/kitty/blob/master/logo/kitty.svg) |

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added
