### ISSUE TITLE
[REQUEST] Icon for Authy app

### ISSUE THREAD

**Issue by amadejpapez** [vinceliuice/WhiteSur-icon-theme#58]
Hi! Only the Authy app is currently missing the correct icon from my dock. Could this be added? It is a pretty popular app for two-factor authentication :)

![image](https://user-images.githubusercontent.com/63184600/120926873-f9262c80-c6de-11eb-8bff-fa40dca36da4.png)

Maybe something similar to [this](https://icons8.com/icon/QHS56jPYqhwb/authy)?

**Comment by amadejpapez** [comment]
@vinceliuice Thank you!!

**Comment by vinceliuice** [comment]
You are welcome!
