### ISSUE TITLE
License: GPL-3 Only or GPL-3 Plus?

### ISSUE THREAD

**Issue by Icy-Thought** [vinceliuice/WhiteSur-icon-theme#62]
Trying to package WhiteSur icon theme for NixOS and after several minutes I had been notified by one of the PR reviewers that the license should be specified as either `gpl3Only` or `gpl3Plus`. 

Due to the lack of such mentions in the license you had specified for this repository, I am here to ask which license we ought to use for the nix package.

Nonetheless, we do appreciate the wonderful icon theme you've shared with the community!

**Comment by hsbasu** [comment]
It's licensed under `GNU-GPL3`. Please check [COPYING](https://github.com/vinceliuice/WhiteSur-icon-theme/blob/master/COPYING) for further informations.

**Comment by Icy-Thought** [comment]
Well, the `gpl3` stands for `GNU GPL-3. 

What is being asked for here is if this license will follow future changes to the `GNU GPL` license or retain its version as a `GNU GPL-3` license, hence `gpl3Only` (v3 only) or `gpl3Plus` (or later).

**Comment by NobbZ** [comment]
You misunderstood something.

The distinction is not about license of this project might Autoupgrade itself (it never does,aas one needs to actively change the license file for a license change).

It is instead important for "derived work". Is derived work allowed to be published under any GPL version that is 3.0 or later or under GPL v3 only?

**Comment by Icy-Thought** [comment]
Re-reading my own explanation, that has indeed been explained wrong, I should've been careful with my choice of words. 

Appreciate the clarification, Nobbz!

**Comment by 06kellyjac** [comment]
After a quick peruse it looks like the section advising headers in source files that says V3 "or(at your option) any later version." remains in the license file.

https://github.com/vinceliuice/WhiteSur-icon-theme/blob/master/COPYING#L637-L640

The header doesn't seem to actually be added to any of the files so of course it's still a good idea to wait for a response from @vinceliuice to clarify

**Comment by vinceliuice** [comment]
GPLv3 or later, not GPLv3 only

**Comment by Icy-Thought** [comment]
I think we can close this issue for now. 
Appreciate the quick answer!
