### ISSUE TITLE
Icon for protonvpn gui

### ISSUE THREAD

**Issue by dbasinge** [vinceliuice/WhiteSur-icon-theme#64]
Needs icon for protonvpn new gui. I have attached a zipped svg for it.

[protonvpn-logo.zip](https://github.com/vinceliuice/WhiteSur-icon-theme/files/6644066/protonvpn-logo.zip)

**Comment by dbasinge** [comment]
[protonvpn-logo.zip](https://github.com/vinceliuice/WhiteSur-icon-theme/files/6644078/protonvpn-logo.zip)
 Different style

**Comment by dbasinge** [comment]
Think icon needs to be named protonvpn-logo to match desktop file.

**Comment by vinceliuice** [comment]
No problem!
