### ISSUE TITLE
[Request] Icons for JabRef, TexMatch, Paperwork, etc.

### ISSUE THREAD

**Issue by domiden** [vinceliuice/WhiteSur-icon-theme#70]
First of all many thanks for your hard work!

I was wondering if you may add icons for the following Applications:

- [JabRef](https://github.com/JabRef/jabref)
- [TexMatch](https://github.com/zoeyfyi/tex-match)
- [Setzer](https://github.com/cvfosammmm/Setzer)
- [Paperwork](https://gitlab.gnome.org/World/OpenPaperwork/paperwork)
- [Foliate](https://github.com/johnfactotum/foliate)
- [Notable](https://github.com/notable/notable)

- [Hugin](http://hugin.sourceforge.net/)
- [FreeCAD](https://github.com/FreeCAD/FreeCAD)

- [Julia](https://github.com/JuliaLang/julia)
- [Fish](https://github.com/fish-shell/fish-shell)

- [Bottels](https://github.com/bottlesdevs/Bottles)
- [Authenticator](https://gitlab.gnome.org/World/Authenticator)

I would appreciate it if you could realise some of them.

**Comment by vinceliuice** [comment]
No problem!
