### ISSUE TITLE
[Request] Support for big icons

### ISSUE THREAD

**Issue by marzuk-zarir** [vinceliuice/WhiteSur-icon-theme#77]
**System tray icons are too small**....please add support for big icons in system tray

**Comment by vinceliuice** [comment]
What's your desktop？

**Comment by marzuk-zarir** [comment]
> What's your desktop？
ubuntu 20.04
gnome shell 3.38

**Comment by vinceliuice** [comment]
Gnome shell only support 16px*16px size symbolic icons on panel, I don't know how to make it support big icons
