### ISSUE TITLE
Bug in install.sh

### ISSUE THREAD

**Issue by carlosala** [vinceliuice/WhiteSur-icon-theme#79]
Hi!
There is a bug in install.sh. The script doesn't have the parameter `-c` or `--color` in its parameters list. It seems to be easy to solve.
Thanks!

**Comment by vinceliuice** [comment]
I'll remove that, -c is not needed, dark version must used with light version

**Comment by carlosala** [comment]
I thought that it was that, so there is a typo in the `install.sh -h`

**Comment by vinceliuice** [comment]
No problem. I will remove that typo

**Comment by carlosala** [comment]
This issue should be closed I think @vinceliuice

**Comment by carlosala** [comment]
@vinceliuice Should be closed, it's been a while since it has been solved
