### ISSUE TITLE
Discord icon issue

### ISSUE THREAD

**Issue by hunabku94** [vinceliuice/WhiteSur-icon-theme#80]
Hi, thanks a lot for your insane work !

In my computer, the discord icon appear like this on panel, menu and icon theme folder thumbnail :
https://imgur.com/jtViRiP

However the file appears correctly in Gimp :
https://imgur.com/HNbtEXW

I tried to install with AUR package and via GitHub clone/install script without any improvement.

**Distribution** : Archlinux
**Kernel** : mainline
**Desktop Environment** : KDE 5.22
**KDE Theme** : WhiteSur-dark
**GTK Theme** : WhiteSur-dark-solid
**Plasma Style** : WhiteSur-dark
**Window Colors** : WhiteSurDark
**Window Decorations** : WhiteSur-Sharp-dark
**Fonts** : Droid Sans / Droid Sans Mono
**Icons** : WhiteSur-dark
**Cursors** : WhiteSur Cursors

**Comment by syndek** [comment]
I'm also seeing this issue, but only in KDE/Plasma applications. Looks like it's something on their end that's causing this.

**Comment by vinceliuice** [comment]
Fixed!

**Comment by syndek** [comment]
Legend, can always count on you Vince! :heart: Thanks as usual.

**Comment by vinceliuice** [comment]
You are welcome!
