### ISSUE TITLE
Please add an icon for "wike"

### ISSUE THREAD

**Issue by AshkanLaei** [vinceliuice/WhiteSur-icon-theme#86]
Hi @vinceliuice 

I wanted to ask you to add an icon for the "Wike" application (a Wikipedia client)

I prefer an icon like the simple Wikipedia logo, a W letter in a white square.

You can also add some details to it. See the following images for example:

![image](https://user-images.githubusercontent.com/50172698/130036949-a2c0dbb5-95e3-45e6-9f7c-78bd5a66d566.png)

![image](https://user-images.githubusercontent.com/50172698/130036888-d6f3440c-ff57-4ef7-8e3d-0fef34466bca.png)

**Comment by aargar1** [comment]
If you could give me a SVG, I could make a pull request :)

**Comment by AshkanLaei** [comment]
I don't have a perfect one but I think this image from Wikimedia is a good one:

![](https://upload.wikimedia.org/wikipedia/commons/3/34/Wikipedia_W_-_SuperTinyIcons.svg)

**Comment by aargar1** [comment]
Done! https://github.com/vinceliuice/WhiteSur-icon-theme/pull/100

**Comment by aargar1** [comment]
For the time being, you can clone https://github.com/aargar1/WhiteSur-icon-theme and install that using the same install script :) You should see the Wike icon

**Comment by aargar1** [comment]
close #86
