### ISSUE TITLE
Icon request: EasyEffects

### ISSUE THREAD

**Issue by v1gnesh** [vinceliuice/WhiteSur-icon-theme#89]
Hi,

Thank you for this project.
When you do the next round of icon additions, please also include this:
https://github.com/wwmm/easyeffects/blob/master/data/easyeffects.svg

**Comment by aliazhar-id** [comment]
![image](https://user-images.githubusercontent.com/58647884/134005174-10e440e1-9c67-4dfe-bc1f-9cefcea15ab9.png)

maybe like this?
(I'm just trying while learning)

**Comment by aargar1** [comment]
I like this icon; Write a pr!

**Comment by aliazhar-id** [comment]
#101

**Comment by aliazhar-id** [comment]
#101
