### ISSUE TITLE
how can i transparent top-bar on elementory Os ?

### ISSUE THREAD

**Issue by Ok9xNirab** [vinceliuice/WhiteSur-icon-theme#9]
![Screenshot from 2020-09-26 19 59 30](https://user-images.githubusercontent.com/40653908/94342469-027cd680-0033-11eb-89a5-1728f468829e.png)

Here top-bar is white , i need to set transparent like default elementory topbar .

Thanks.

**Comment by joe733** [comment]
Hello, that is changed using a GTK+ theme not icon theme.. You might want to open issue in another repository.
