### ISSUE TITLE
Dark icons don't show/work 

### ISSUE THREAD

**Issue by agam778** [vinceliuice/WhiteSur-icon-theme#92]
First of all, thanks a lot for this great work ❤️

But actually I have this issue:
I installed WhiteSur Icon Theme and then selected the dark mode but it still shows the light mode icons
![image](https://user-images.githubusercontent.com/68941022/132819023-3b567896-b44f-442d-8f18-6ba1c1a398aa.png)

Hope you fix it!

**Comment by vinceliuice** [comment]
Dark icon only for panel icon, app icons don't have dark mode

**Comment by agam778** [comment]
But like here the VSCode etc. have dark icon?
![image](https://user-images.githubusercontent.com/68941022/132855373-b02dbd3f-b56d-46b5-b589-2fc9f4f2f8d6.png)

**Comment by vinceliuice** [comment]
I'll change it back
