### ISSUE TITLE
Icon request: Fish Shell, Linux Mint, Plex, Rclone

### ISSUE THREAD

**Issue by slgobinath** [vinceliuice/WhiteSur-icon-theme#98]
Hi,
First of all thank you so much for this awesome icon pack. The following apps don't have WhiteSur icons in my system.
- Mint Welcome: `mintwelcome`
- Plex Media Server: `plexmediaserver`
- Fish Shell: `fish`
- Rclone Browser: `rclone-browser`
- [Safe Eyes](https://github.com/slgobinath/SafeEyes): `safeeyes`, status icons: `safeeyes_enabled`, `safeeyes_disabled` (I'm the developer of Safe Eyes. If time permits, I will work on an SVG icon)
- [Notable](https://notable.app/): `notable`
- [Warpinator](https://github.com/linuxmint/warpinator): `org.x.Warpinator`
- [Bulky](https://github.com/linuxmint/bulky): `bulky`

I've created the icons for the first four apps by modifying the existing icons and attached them here. Designing is far from my expertise. Feel free to modify them or create your own.

![image](https://user-images.githubusercontent.com/4003168/134755321-1e0c3fc3-8840-4975-8564-66b2487c9bb9.png)

SVG files: [icons.zip](https://github.com/vinceliuice/WhiteSur-icon-theme/files/7229054/icons.zip)

**Comment by vinceliuice** [comment]
Thanks!

**Comment by vinceliuice** [comment]
I'll add them

**Comment by slgobinath** [comment]
@vinceliuice thanks for such a quick update. All look fantastic. Especially the Safe Eyes icon.

**Comment by vinceliuice** [comment]
You are welcome!
