### ISSUE TITLE
Icon request: sqlitebrowser, Citrix, ULauncher, WebApps

### ISSUE THREAD

**Issue by slgobinath** [vinceliuice/WhiteSur-icon-theme#99]
Hi, Last time I missed some icons in the issue. So I am opening this issue with the new list of missing icons on my Linux Mint Cinnamon system.
[SQLite Browser](https://sqlitebrowser.org/): `sqlitebrowser`
[Citrix](https://chrome.google.com/webstore/detail/citrix-workspace/haiffjcadagjlijoggckpgfnoeiflnem?hl=en): `chrome-haiffjcadagjlijoggckpgfnoeiflnem-Default` This is a desktop entry created for Chrome app.
Graphics Tablet: `cs-tablet` - A cinnamon tool to configure tablets like Wacom
[ULauncher](https://ulauncher.io/): `ulauncher`
WebApps: `webapp-manager` - A cinnamon tool to convert websites into desktop apps using a browser

Thanks in advance

**Comment by aargar1** [comment]
I use a lot of the same apps, however, it's hard to find icons. If you could send them, I can write a pr!

**Comment by aargar1** [comment]
I found this for the db browser, but the rest I cannot find! https://media.macosicons.com/parse/files/macOSicons/29b9086e614591a5b2b966cd20e4286a_low_res_DB_Browser_for_SQLite.png

**Comment by slgobinath** [comment]
@aargar1 nope. I'm working on some icons but I opened this issue in case @vinceliuice has a better idea.

**Comment by slgobinath** [comment]
@aargar1 I've opened a PR for all except the Graphics Tablet icon
